### ISSUE TITLE
[友链] AirXplor

### ISSUE THREAD

**Issue by ExDragine** [jinzhijie/jinzhijie.github.io#1]
> 本issue专门处理友链问题

**格式**

- 标题(可选带链接)
- 链接
- 图标

示例

[AirXplor](https://airxplor.design/)
https://airxplor.design/
https://airxplor.design/wp-content/uploads/2020/01/AirXplor-300x300.png

**Comment by jinzhijie** [comment]
可选- 简单描述

**Comment by jinzhijie** [comment]
added in commit a84c05a，页面待改进
